### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by alanetsai** [kimballXD/box_office#1]
全國電影票房截至2017年四月前資訊 | 33.pdf | 3 | 21 | 日本 | 巧虎繪本王國歷險記 | 2017-01-13 | 84 | 15 | 16005 | 3562827 | False

全國電影票房截至2017年四月前資訊
21 日本 | 巧虎繪本王國歷險記 | 2017/01/13 | 65 | 46 | 26,492 | 6,003,561
22 丹麥 | 拆彈少年 | 2017/01/13 | 84 | 15 | 16,005 | 3,562,827

抓到下一格的資料了

**Comment by kimballXD** [comment]
感謝回報！
已確認原因為 PDF 解析成 html 時，字串格式與先前不一致，造成 regular expression 解析錯誤

- Root Cause

此檔案 PDF 解析結果截錄
> 22 21 日本
> 23 巧虎繪本王國歷
> 24 險記
> 25 2017/01/13
> 26 全民大劇團股份有限
> 27 公司
> 28 株式会社ベネッセコーポ
> 29 レーション
> 30 65 46 26,492 6,003,561
> 31 22 丹麥 拆彈少年 2017/01/13
> 32 傳影互動股份有限公
> 33 司
> 34 (德國)K5 MEDIA GROUP
> 35 GMBH
> 36 84 15 16,005 3,562,827

程式目前是以 [ `re.match(u'^(\d{1,3})$', x.text) or re.match(u'^(\d{1,3})\s+(\W+)$', x.text)` ](https://github.com/kimballXD/box_office/blob/acfc37943174480d6ae64c6f5c9dca523c53ed49/box.py#L87)
來識別記錄開頭的行號。
但此檔案的記錄 22 ，記錄開頭的格式卻是 `22 丹麥 拆彈少年 2017/01/13` (31 行)
這不符合目前任何一個 regular expression pattern，故造成此筆記錄識別失敗。

- Impact

此類解析錯誤將造成兩種問題
(1) 識別失敗的記錄將不會出現在解析結果中。以 bug 回報案例為例，最後解析結果不會有「拆彈少年」的記錄。經查，box.csv 因此短少了約100 條左右的記錄。

(2) 識別失敗紀錄的前一條記錄，其票房數據會錯置成識別失敗紀錄的票房數據。以 bug 回報案例為例， 巧虎繪本王國歷險記的票房數據被錯置為 36 行 拆彈少年的數據。

- Solution

經檢視後，此檔案有很多記錄都解析成 `編號 國別 片名 日期` 的格式
故決定修改 regular expression pattern 來解決解析錯誤問題，預計修改為：
``re.match(u'^(\d{1,3})$', x.text) or re.match(u'^(\d{1,3})\s+(\W+)(\d{4}/\d{2}/\d{2})?$', x.text)``

另外，為避免類似狀況再度發生，之後將實作「行數檢查」的功能：
若發現 parsing 結果記錄編號不連續，程式將拋出 exception ，
令使用者能在第一時間發現、處理解析錯誤

**Comment by kimballXD** [comment]
fixed and close!
